export const mockText = `
Aliquam commodo luctus enim, vel porta massa maximus nec. Fusce auctor, leo eget consequat facilisis, augue urna sodales tellus, at commodo justo nibh non lectus. Pellentesque ac dolor sed odio molestie lacinia. Etiam suscipit ligula quis augue gravida, id pellentesque metus placerat. Nunc mattis leo lorem, eu pharetra enim euismod a. Nulla mollis arcu non urna sollicitudin pulvinar. Praesent eget ligula odio. Phasellus feugiat enim nisl, vitae dignissim neque suscipit eu. Nunc massa sapien, maximus id erat in, ornare convallis ex
AAPL GOOGL
`;

// export const mockText = `
//  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras turpis risus, ullamcorper at est in, porttitor hendrerit nibh. Quisque lobortis, tellus sed volutpat vestibulum, eros nisi egestas eros, ac maximus erat purus at ante. Quisque iaculis, lorem sit amet ultrices mollis, lacus dolor molestie enim, sed pulvinar dui lacus id lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt condimentum malesuada. Phasellus eget est ac arcu placerat malesuada eget non sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam sagittis, arcu ac porttitor sollicitudin, metus risus ullamcorper mauris, ut porta nibh tortor id diam. Quisque pretium, nulla eget lacinia pulvinar, ipsum massa elementum augue, non ultrices diam ante ut leo. Pellentesque tincidunt in ex sed aliquam. Suspendisse potenti. Fusce pharetra tempus felis, ut pulvinar sem rutrum id.

// Nunc porta, odio eu viverra ornare, arcu odio ultricies ex, sit amet ullamcorper dui erat vitae ligula. Pellentesque ullamcorper lacus sed blandit congue. Nullam sit amet volutpat lorem, ut porttitor felis. Aenean cursus dictum dui in cursus. Donec consectetur massa ac lorem egestas placerat. Aenean nunc nibh, rutrum at urna id, sodales viverra eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et maximus risus, sit amet imperdiet tellus. Vivamus ultrices, sem ut mattis efficitur, arcu diam pharetra ex, in mollis mi justo eget metus. Nunc vulputate est dolor, non molestie leo iaculis sit amet.

// Aliquam commodo luctus enim, vel porta massa maximus nec. Fusce auctor, leo eget consequat facilisis, augue urna sodales tellus, at commodo justo nibh non lectus. Pellentesque ac dolor sed odio molestie lacinia. Etiam suscipit ligula quis augue gravida, id pellentesque metus placerat. Nunc mattis leo lorem, eu pharetra enim euismod a. Nulla mollis arcu non urna sollicitudin pulvinar. Praesent eget ligula odio. Phasellus feugiat enim nisl, vitae dignissim neque suscipit eu. Nunc massa sapien, maximus id erat in, ornare convallis ex. Proin mollis elit sed leo fermentum pretium. Suspendisse potenti. Suspendisse potenti.
// AAPL GOOGL
// Aliquam erat volutpat. Pellentesque varius nisl neque, vel porta justo elementum id. Nam nec sem tortor. Fusce convallis consequat libero, et maximus nulla maximus ut. Vestibulum eu blandit sapien. Praesent massa sapien, consequat in efficitur et, pretium eu sapien. Donec diam lectus, lobortis eget sapien sit amet, semper tristique sem. Vestibulum tincidunt sapien urna, volutpat bibendum erat vulputate eu. Donec mattis congue nisl eget rutrum. Phasellus fermentum feugiat nibh, id auctor odio dictum ac. Donec molestie consectetur feugiat.
// FACEBK

// Pellentesque in sapien porta, accumsan nisi sed, ornare sapien. Donec dictum, sapien sit amet dapibus mollis, ex turpis imperdiet tellus, at tincidunt nisl libero sit amet nisi. Integer elementum suscipit neque vel elementum. Duis tempus augue non tincidunt scelerisque. Nullam non luctus justo, at laoreet est. Donec quis lacus ac nunc rutrum pulvinar non eu lectus. Vestibulum rhoncus erat metus, et bibendum velit molestie vel. Praesent sit amet ante aliquet, condimentum massa vitae, iaculis sem. Donec ut tempor libero. Sed vulputate lacus sed diam porttitor imperdiet. Aenean imperdiet rutrum nulla quis mollis. Aliquam maximus ac risus quis egestas. Mauris risus nibh, dapibus in aliquet at, cursus sagittis urna. Duis pharetra ipsum at dui lobortis convallis. Aliquam pretium ultrices venenatis. Integer id euismod nulla, eu vulputate urna.
// `;
